### ISSUE TITLE
Any div is not displaying in the expansion due to css property

### ISSUE THREAD

**Issue by chinshaw** [GwtMaterialDesign/gwt-material-table#10]
table.table tbody tr.expansion td  div {
   max-height: 0;
}

This causes any div to not display in the view. I was able to resolve the issue and make the expand animation work correctly by adding a descendent selector.  

table.table tbody tr.expansion td > div {
   max-height: 0;
}

Note this is probably releated to issue #2 MaterialButton Icon not displaying. I can put together a pull request later on this weekend.

**Comment by BenDol** [comment]
Ah, nice catch! I was actually doing it this in other areas not sure why I missed this one haha.
