### ISSUE TITLE
ColumnMenuIcon 2.0-SNAPSHOT no functionality

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material-table#102]
Hi,
Since 2.0-SNAPSHOT\gwt-material-table-2.0-20170824.233802-89.jar there is no functionality
on the ColumnMenuIcon anymore.
Thanks
![columnmenuicon](https://user-images.githubusercontent.com/24357072/30067597-80ceb3d0-925b-11e7-95e5-5d319616729f.PNG)

**Comment by BenDol** [comment]
Should be resolved in the latest snapshot, can you confirm? Thanks

**Comment by HoochSDS** [comment]
Hi, 
2.0-SNAPSHOT\gwt-material-table-2.0-20170924.112902-100.jar is working.  :thumbsup:
Thanks
