### ISSUE TITLE
MaterialCheckBox can't be checked in a MaterialDataTable

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material-table#104]
A MaterialCheckBox added to a MaterialDataTable using a Widget column can't be clicked.

Other widgets, like MaterialComboBox or MaterialTextBox can be used.

**Comment by rmraya** [comment]
You can test this issue at https://dev.maxprograms.com/TestCase/ 

Java source and UiBinder XML ara available from the page.

**Comment by BenDol** [comment]
Can you retest this on the latest snapshot? Should be resolved.

**Comment by rmraya** [comment]
Hi,

It's fixed in latest snapshot. Thanks!
