### ISSUE TITLE
project broken in branch release_2.0

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material-table#113]
Can't compile gwt-material-table due to changes in gwt-material.

src/main/java/gwt/material/design/client/ui/table/AbstractDataTable.java calls build() in line 182 but method build() doesn't exist.

**Comment by rmraya** [comment]
The log from Maven is available at https://dev.maxprograms.com/table_error.log

**Comment by kevzlou7979** [comment]
Im working now on phase 2 of the implementation of the rework.

**Comment by kevzlou7979** [comment]
If the Continuous Integration and tests are ok , then we will merge this https://github.com/GwtMaterialDesign/gwt-material-table/pull/112

**Comment by BenDol** [comment]
Should be resolved. Can you confirm everything is okay for you?

**Comment by rmraya** [comment]
Project compiles without errors now. Thank you!
