### ISSUE TITLE
Branch release_2.0 fails Surefire tests

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material-table#115]
Build fails in branch release_2.0 with today's changes. See attached log

[table_log.txt](https://github.com/GwtMaterialDesign/gwt-material-table/files/1391875/table_log.txt)

**Comment by rmraya** [comment]
Attached failed test results

[gwt.material.design.client.ui.table.MaterialDataTableTest.txt](https://github.com/GwtMaterialDesign/gwt-material-table/files/1391968/gwt.material.design.client.ui.table.MaterialDataTableTest.txt)
[gwt.material.design.client.ui.table.MaterialInfiniteDataTableTest.txt](https://github.com/GwtMaterialDesign/gwt-material-table/files/1391969/gwt.material.design.client.ui.table.MaterialInfiniteDataTableTest.txt)

**Comment by kevzlou7979** [comment]
Fixed via http://127.0.0.1:8888/index.html
