### ISSUE TITLE
Fields overlap on iphone

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material-table#127]
Tested with iphone 6/7 both chrome & safari.  Table is unusable, as seen in screenshot:

![image](https://user-images.githubusercontent.com/18280223/34081000-0dd7bb1e-e347-11e7-8057-42b1915181b6.png)

**Comment by simerlec** [comment]
This has already been reported - see here.

https://github.com/GwtMaterialDesign/gwt-material-table/issues/38

**Comment by kevzlou7979** [comment]
Closing this as it was a duplicate of #38
