### ISSUE TITLE
MaterialDataPager: onLoad reinitialises the pager state, which is highly undesirable

### ISSUE THREAD

**Issue by Hoagiex** [GwtMaterialDesign/gwt-material-table#13]
Reattach/onLoad of the MaterialDataPager widget, should not lead to re-initialization on state on the pager.

if it has been previously attached, that state should be persistent, if the user navigates away from the page and later return to that page, if no new MaterialDataPager object needs to be constructed (example case: @Singleton pages with Errai)

**Comment by kevzlou7979** [comment]
@Hoagiex Thanks for catching this, I think what will be the solution is to do check on ```onLoad```
Like for example :

``` java

@Override
public void onLoad() {
    if (!initialized) {
        // TODO the initialization method
        initialize();
        initialized = true;
    }
}

```

**Comment by BenDol** [comment]
Is this still happening in 2.0?

**Comment by BenDol** [comment]
See https://github.com/GwtMaterialDesign/gwt-material-table/issues/11
