### ISSUE TITLE
MaterialTable - Solution for Mobile view 

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#134]
Here's I've got in my RnD for Responsive DataTable. Feel free to discuss and analyze the benefits of this codepen.

https://codepen.io/zavoloklom/pen/IGkDz?editors=1010

**Comment by kevzlou7979** [comment]
Found something interesting article https://css-tricks.com/responsive-data-tables/

**Comment by BenDol** [comment]
This is basically how the current data table it set up to respond to mobile. It might be that it just needs to some tweaking and fixes for specific browsers. It also depends what container the table is in and how its CSS rules are set up.

**Comment by BenDol** [comment]
You can test this by adding the MaterialDataTable to the body element at 100% width and scale the browser.

**Comment by kevzlou7979** [comment]
Yeah agreed we can look how to respond to i'ts container but I think its just a plain css with media query. Also found out that the table headers is defined on the css which I think is hard coded. Might be good to define it directly to the DOM.

**Comment by BenDol** [comment]
Yes that is currently how the existing data table works. See https://github.com/GwtMaterialDesign/gwt-material-table/blob/master/src/main/resources/gwt/material/design/client/resources/css/style.css#L487 there are multiple definitions like so.

**Comment by kevzlou7979** [comment]
![categorized](https://user-images.githubusercontent.com/3138071/36053153-77e53e64-0e2b-11e8-984e-be91c134cbb9.gif)
![paged](https://user-images.githubusercontent.com/3138071/36053154-781fbb70-0e2b-11e8-9757-da003501b51b.gif)
![row-expansion](https://user-images.githubusercontent.com/3138071/36053156-7863d58a-0e2b-11e8-80d1-556991e4d0ca.gif)
![selection](https://user-images.githubusercontent.com/3138071/36053157-78a0da84-0e2b-11e8-8698-2eb0ad1fd0a3.gif)
![simple](https://user-images.githubusercontent.com/3138071/36053158-78dc7422-0e2b-11e8-9855-4acbe2164575.gif)
