### ISSUE TITLE
MaterialDataTable - Can't apply selection on checkbox.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#137]
Hi @BenDol ,

I just noticed that if I select the rows directly to the checkbox, the selection can't be made. But selecting the rows area is working fine.

Thanks,
Mark

**Comment by BenDol** [comment]
What device? I have tested it on Chrome and it seems fine.

**Comment by kevzlou7979** [comment]
Desktop devices, Chrome tested on Ubuntu.

**Comment by kevzlou7979** [comment]
Ok tested the checkbox selection on Windows but still the checkbox is not clickable only the rows

![table-2](https://user-images.githubusercontent.com/3138071/36129389-e7c69d68-10a1-11e8-8876-75a7e52677e2.gif)

**Comment by BenDol** [comment]
Will take a look, thanks for the info.
