### ISSUE TITLE
infinity table with request factory

### ISSUE THREAD

**Issue by yogitjain** [GwtMaterialDesign/gwt-material-table#14]
I have tried Infinity datatable with request factory but its not working for me can you please prepare a example of infinity table with request factory.

**Comment by BenDol** [comment]
The way it works isn't specific to the transfer protocol you are using so taking the sample from the sample app and replacing the async call with the Request Factory call will work assuming you are providing all the required data for the infinite data source.

**Comment by BenDol** [comment]
See for reference:
* [InfiniteTable.java](https://github.com/GwtMaterialDesign/gwt-material-table-sample/blob/master/src/main/java/gwt/material/design/sample/client/ui/InfiniteTable.java)
* [PersonDataSource.java](https://github.com/GwtMaterialDesign/gwt-material-table-sample/blob/master/src/main/java/gwt/material/design/sample/client/ui/datasource/PersonDataSource.java)

So where its making the async call [here](https://github.com/GwtMaterialDesign/gwt-material-table-sample/blob/master/src/main/java/gwt/material/design/sample/client/ui/datasource/PersonDataSource.java#L32) can be any kind of transfer service so long as you .invoke the
```java
dataView.loaded(startIndex, people, people.getAbsoluteTotal(), true);
```
Inside the finish of the async call.

**Comment by yogitjain** [comment]
Hello BenDol,
I am new in GWT and My RF( request factory) object is in my presenter and I need these it my view.java file for pass it into acync datasource before ui binding ( i mean in constructor) can you please help me find a way to do this .
thank you very much for your quick reply.
thanks

**Comment by yogitjain** [comment]
Hello BenDol,
I am still waiting for solution of  infinity datatable with pagination. I have implemented datatable but pagination is not working properly . May be I have made some mistakes in implementation but I am unable to identify it. so I am requesting you to guide me.
issues I have faced in pagination was .
a> if I have 80 records in data base and for example first time it loads 20 records and i scroll it down it will fire a ajax but requested range is always started from 0 ( ideally it should be 21 )
b> if I resize my screen then requested range had changed ( e.g before resize requested range is 0,20 and after resize it was 0,12)

**Comment by BenDol** [comment]
If you want to use async pagination then you can now do so with the latest SNAPSHOT changes, just need to setup your DataSource to run your async call and configure appropriately as seem in the sample application. Personally I think pagination is redundant when you can just use the infinite scrolling technique, but I guess some people still like it for what ever reason.

**Comment by BenDol** [comment]
To address the request range issue, you have it set to DYNAMIC_VIEW meaning it will adapt the size based on the screen size. You can hard set this view size either calling setViewSize on the InfiniteDataView or as one of its construction parameters is `int viewSize`.

The first issue about where the data always starts means you are not using the correct values to request your data from your external data source. All of the values you should need like offset, limit, etc are all provided for you to make calls to your data source and update the table.
