### ISSUE TITLE
CategoryComponent - openByDefault does not open the category

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#144]
Hi @BenDol ,

Just notice the category component does not open by default event I've set it to true.

Best Regards,
Mark

**Comment by BenDol** [comment]
This is working when I test it, how are you implementing this? You might be assigning it after the category has already been created and rendered perhaps.

**Comment by kevzlou7979** [comment]
It's working now, yeah true needs to assign it after the category has been rendered.
