### ISSUE TITLE
DataTable - Horizontal Scroll is not visible on second attach.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#145]
Hi @BenDol ,

Just tested the DataTable (Any type) - when trying to load it the first time, the horizontal scroll is visible but when I navigate to any page then bring back the DataTable - the horizontal scroll will now hidden. Just notice that the width is lesser than before. 

![table-1](https://user-images.githubusercontent.com/3138071/36129166-c4e3a4e0-10a0-11e8-94f3-f83f180366d1.gif)

Best Regards,
Mark

**Comment by BenDol** [comment]
Ah good catch this is the same issue we were having, but since the table load isnt invoked we arent reassigning the scroll bar.
