### ISSUE TITLE
weird appearance in mobile scenario

### ISSUE THREAD

**Issue by Magallo** [GwtMaterialDesign/gwt-material-table#150]
Hi all, I'm using this great GWT Material framework for my latest application and I think it's great. However I have used MaterialDataTable component in some of my pages and I discovered, when showing the webapp on my smartphone, that the datatable looks horrible. For some reasons the layout is completely misaligned and the rows are rendered vertically instead of horizontally. 

So I tried to show the GWT Material Showcase on my smartphone and also using the showcase app, the datatable is completely weird. See attached image to see what I mean.

Is MaterialDataTable still under development for mobile use and are you conscious of this problem, or is there something I am missing? What are the future plans for this component? I think it's very interesting, it has also a very interesting support for deciding whether or not a column could be visible depending on the size of the screen (via the hideOn() override method of columns), so I guess the mobile support is expected.

What could we do to let the MaterialDataTable component be usable in a mobile scenario?

Thanks. Ciao.
![img_0271](https://user-images.githubusercontent.com/19425083/38426512-2b229380-39b7-11e8-8adf-7f87e1a984f2.PNG)

**Comment by BenDol** [comment]
HI @Magallo this mobile glitch is a known issue in the current version of the demo application. The latest version of the data table will have some reworks to the demo app to resolve this mobile glitch.
