### ISSUE TITLE
MaterialDataTable sort very slow

### ISSUE THREAD

**Issue by stockiNail** [GwtMaterialDesign/gwt-material-table#153]
I'm using the MaterialDataTable with 12 columns and 85 rows.
The columns are sortable.
When I'm requesting the sort for a column, the sort last 17 seconds.
This is happening if I'm using both Firefox and IE.

Here is the definition of material data table:
<MaterialDataTable ui:field="table" m:id="instancesTable" useCategories="false" 					useRowExpansion="false" useLoadOverlay="true" useStickyHeader="true"> 

I'm using GWT material 2.0.1.

**Comment by BenDol** [comment]
This is a known issue in Firefox and IE, need people to help investigate this issue for a solution. I will be looking into it this week, but any help prior will help speed up a solution. Thanks!

**Comment by BenDol** [comment]
I have begun investigating sort performance on Firefox and IE, [this commit](https://github.com/GwtMaterialDesign/gwt-material-table/commit/99e113610a29a930951e31bfa3c452c68dd68a28) will help improve performance but there is still a rendering issue on those browsers that needs to be identified.
