### ISSUE TITLE
Intializing table in GWTP - best practics

### ISSUE THREAD

**Issue by Hacker-CB** [GwtMaterialDesign/gwt-material-table#19]
In all examples table is initialized inside Composite widget in onLoad().
I'm using GWTP and I have tried to initialize table inisde View constructor but failed because widget is not attached to DOM in this time.
Which is the better place to initialize table inside GWTP view if I don't want to create Composite widget for each table?

**Comment by BenDol** [comment]
If I remember correctly a GWTP view has an onAttached method that is called when the View is attached.

Verified here: https://github.com/ArcBees/GWTP/blob/master/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/client/ViewImpl.java#L188

**Comment by Hacker-CB** [comment]
You are right, but onAttach() method is called every time presenter will be put to slot.
So in this case I need do something like:
```
...
private boolean initDone=false;
...
protected void onAttach(){
   if (initDone) return;
   ...
   table.addColumn(...);
   initDone=true;
}
```

Seems that it is not looks nice...

**Comment by BenDol** [comment]
I will consider making it possible to initialize the table before the DOM has been attached. Will look into that over the next few days.

**Comment by BenDol** [comment]
Fixes are in the latest SNAPSHOT and the rc6
