### ISSUE TITLE
 MaterialDataTable(scaffolding) is using default

### ISSUE THREAD

**Issue by duststar76** [GwtMaterialDesign/gwt-material-table#202]
`   public AbstractDataTable() {
        this(new StandardDataView<>());
    }

    public AbstractDataTable(DataView<T> view) {
        this(view, new DefaultTableScaffolding());
    }

    public AbstractDataTable(TableScaffolding scaffolding) {
        this();
        this.scaffolding = scaffolding;
    }`
Within the AbstractDataTable the constructor change is leading to use the DefaultTableScaffolding.

**Comment by kevzlou7979** [comment]
Updated https://github.com/GwtMaterialDesign/gwt-material-table/pull/200
