### ISSUE TITLE
Striped style not applied

### ISSUE THREAD

**Issue by andreaht** [GwtMaterialDesign/gwt-material-table#206]
"striped" style is not applied in GMD Table if selection type is set to "NONE".
Can be reproduced here: https://gwtmaterialdesign.github.io/gmd-table-demo/#customized

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-table/commit/80647ee8c68295ac0671522d0b57578f0baf7b36
