### ISSUE TITLE
Table is loaded several times

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material-table#28]
Hello. I did some tests with the DataTable (1.0-rc3) addin and there is a strange issue.
Every time onLoad() is called the tabel is loading again. In a GWTP application onLoad() is called every time
you navigate back to the "DataTabel". --> (Same behavior in gwt-material-demo)

My Question is, how do remove (clear) the old DataSource from the table, and how do you prevent to load the table again:

On gwt-material-demo-master (Code): 

```
  //List<Person>
  dataSource.remove(people);   // no effect, where to place?
```
```
  // Load the table again (GWTP)
  @Override
  protected void onLoad() {
    super.onLoad();
    // Loading Column again
    table.addColumn(new TextColumn<Person>() {
      @Override
      ...
```
Thanks

![Image of DataTable](https://files.gitter.im/GwtMaterialDesign/gwt-material/fW5C/MaterialDataTable.jpg)

**Comment by BenDol** [comment]
Added a temporary workaround for `addColumn` will rework it later to render columns/headers separately to this call. Use the following anywhere you require it: (obviously not in onLoad)
```java
table.addLoadedCallback(()-> {
   table.addColumn(...);
   ...
});
```
This will fire when a table is loaded. On the latest snapshot it will also deal with table tear downs better.
