### ISSUE TITLE
How to remove all rows from a table

### ISSUE THREAD

**Issue by eliseurm** [GwtMaterialDesign/gwt-material-table#29]
I would like to know if there is a direct way to remove all rows from a table.

ex:
table.removeAll();

**Comment by eliseurm** [comment]
I've tried several possibilities.

1)
`table.clear();`
- Doing so, it removes the entire table, and after using this method I can no longer include new lines using `table.setRowData(0, list);`

2)
`table.setRowData(0, newArrayList<DataItem>();`
Doing so, nothing happens.

3)
```
int max = table.getSelectedRowModels(true).size ();
For (i = 0; i <= max; i++) {
   table.remove(i);
}
```
- Thus making him some error and for the system;


Would it be possible for you to implement an example of how to pull one, several, or all rows from a table at https://github.com/GwtMaterialDesign/gwt-material-table-sample?

Thank you very much in advance

**Comment by BenDol** [comment]
Addressed here https://github.com/GwtMaterialDesign/gwt-material-table/commit/c442613ac3475b7cb6d6905558376cb44a2c35c4

**Comment by eliseurm** [comment]
Friend, if you can implement it too, there is still a `table.removeRow(index);`
