### ISSUE TITLE
setTableIcon(), setStretchIcon() missing

### ISSUE THREAD

**Issue by kyr0** [GwtMaterialDesign/gwt-material-table#3]
At the moment I see no way to change the table header's icon (or hide it);
I also see no way of hiding the stretch icon (fullscreen/maximize).

**Comment by BenDol** [comment]
These can be found in [MaterialDataTable](https://github.com/GwtMaterialDesign/gwt-material-table/blob/master/src/main/java/gwt/material/design/client/ui/table/MaterialDataTable.java). Just call getTableIcon() and alter it as required (hide, change icon, etc).

**Comment by kevzlou7979** [comment]
Also u can acces the table specific section panels by calling
table.getScaffolding ()

On Jul 21, 2016 11:12 PM, "Ben Dol" <notifications@github.com> wrote:
>
> These can be found in MaterialDataTable. Just call getTableIcon() and
alter it as required (hide, change icon, etc).

**Comment by kyr0** [comment]
Ahh, I'm sorry. Thanks for pointing this out. The getScaffolding() I found already to put a button there for Excel export ;-)

**Comment by kevzlou7979** [comment]
Yeah no prob, I will include the specific usecase documentation on GMD Demo
Showcase I'll just wiring up those docs now
