### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insert_11_g$' of undefined

### ISSUE THREAD

**Issue by drmzperx** [GwtMaterialDesign/gwt-material-table#31]
Hi!

When I try to create a GMDT according to the demo I always get the following error:

Uncaught TypeError: Cannot read property 'insert_11_g$' of undefined
    at nag_g$.A2f_g$ [as addHeader_0_g$] (AbstractDataView.java:1849)
    at nag_g$.B3f_g$ [as insertColumn_6_g$] (AbstractDataView.java:846)
    at wDg_g$.nBg_g$ [as insertColumn_6_g$] (AbstractDataTable.java:406)
    at wDg_g$.FDg_g$ [as insertColumn_6_g$] (MaterialDataTable.java:185)
    at wDg_g$.AAg_g$ [as addColumn_8_g$] (AbstractDataTable.java:401)
    at wDg_g$.zAg_g$ [as addColumn_7_g$] (AbstractDataTable.java:396)
    at pRi_g$.C$i_g$ [as onLoad_1_g$] (DashboardTableView.java:142)

And stop the code in line:

table.addColumn(new WidgetColumn<Person, MaterialImage>() {...

I use the latest versions and inherent the following modules:

	<inherits name="gwt.material.design.GwtMaterialWithJQueryDebug"/>
	<inherits name="gwt.material.design.addins.GwtMaterialAddinsDebug"/>
	<inherits name="gwt.material.design.GwtMaterialTableDebug"/>
	<inherits name="gwt.material.design.jquery.JQuery" />

The table codes are running after created the view: view = uiBinder.createAndBindUi(this);

Unfortunately I have no idea whats wrong in my code.

Thanks!

**Comment by axls** [comment]
Make sure that the table is attached (by adding in parent container, for example) before calling table.addColumn.

**Comment by drmzperx** [comment]
I use the following uibuider code:

<ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
	xmlns:g='urn:import:com.google.gwt.user.client.ui' xmlns:m="urn:import:gwt.material.design.client.ui"
	xmlns:combobox="urn:import:gwt.material.design.addins.client.combobox"
	xmlns:w="urn:import:com.xunox.sewicowebapp.client.widgets"
	xmlns:m.table='urn:import:gwt.material.design.client.ui.table'>

	<m:MaterialContainer ui:field="content">
		<m:MaterialRow>
			<m:MaterialColumn grid="s12 m6 l4">
				<combobox:MaterialComboBox ui:field="cbLocation" />
			</m:MaterialColumn>
			<m:MaterialColumn grid="s12 m6 l4">
				<combobox:MaterialComboBox ui:field="cbSensorType" />
			</m:MaterialColumn>
		</m:MaterialRow>
		<m:MaterialRow ui:field="rowTable" />
		<g:HTMLPanel>
		    <m.table:MaterialDataTable ui:field="table"
                               shadow="1"
                               height="calc(100vh - 131px)"
                               useStickyHeader="true"
                               useCategories="false"
                               useRowExpansion="true"
                               selectionType="SINGLE"/>
        </g:HTMLPanel>
	</m:MaterialContainer>
</ui:UiBinder>

and in java code bind the table with

	@UiField
	MaterialDataTable<Person> table;

command.

After run the web app the table main header show correctly, but get an error see earlier and the generated data (the same as demo) are not shown.

**Comment by axls** [comment]
I think you have to move table initialization code (table.addColumn and so on) in overrided onLoad method of the DashboardTableView.

**Comment by drmzperx** [comment]
I use mvp4gwt framework, and when I change the table initialization from view to presenter after call the:

view.asWidget()

method the table fill the data correctly. So you right, thank your help!
