### ISSUE TITLE
Is it possible to access a row's model object during row expansion?

### ISSUE THREAD

**Issue by mitchmartin** [GwtMaterialDesign/gwt-material-table#32]
Following your row expansion example, I'd like to make an async call to retrieve additional information about a row's model when the row is expanded. However, your example doesn't show how you would retrieve information about the row's data in order to make such a request, and I've not been able to find the answer myself. Is this possible?

Thanks

**Comment by mitchmartin** [comment]
Hi, can anyone answer this question? Is it possible to access a row's model object during row expansion, or is this not yet supported?

**Comment by BenDol** [comment]
Sorry for the late response! Resolved here https://github.com/GwtMaterialDesign/gwt-material-table/commit/9b6eb33fd4aa600bb9be5ad5c20ac313fefd063e
