### ISSUE TITLE
Remote Sort should not render rows, probably

### ISSUE THREAD

**Issue by bohdan-petrovskyy** [GwtMaterialDesign/gwt-material-table#35]
Currently I use MaterialInfiniteDataTable that uses always Remote sort and this is great. 
What I can not understand is why there is a need to invoke method renderRows(rows) inside AbstractDataView.sort(...) method? I suppose (but I am not sure, please correct me ) that this method (renderRows(rows)) is odd when InfiniteDataView is used. In a table where I have about 85 columns and initially about 26 rows after I click on some header to sort  - there is some delay (it takes about 7-8 sec) until asc/desc row appears on header and request for new sorted data is sent. After I try to debug what is going on under the hood I have found that renderRows(rows) is the most time consumable method and depends on the number of RomComponent`s that is has to render(for a table with e.g. 20 columns this delay is not so visible).

Another problem with Remote sort is cached rows on client side. Looks that if we have sorted our table, we do not have to check if we have cached rows on client but load rows from data source always. In other case row with incorrect order are shown in table until we load the new (non-cached) rows from data source.

**Comment by BenDol** [comment]
Both issues here have been addressed in the latest SNAPSHOT changes.

**Comment by bohdan-petrovskyy** [comment]
thanks a lot!
