### ISSUE TITLE
DATA TABLE - WIDGET COLUMN 

### ISSUE THREAD

**Issue by gaston2303** [GwtMaterialDesign/gwt-material-table#36]
Good morning_afternoon,

I would like to know how keep the values in column of a table. The field is MaterialTimePicker data type.

I created the column like this:

endtime = new WidgetColumn<Trabajo, MaterialTimePicker>() {
					@Override
					public MaterialTimePicker getValue(Trabajo object) {

Which event do I have to create in order to obtain the value set? To after work with the data.

Thank you very much. 
Gastón

**Comment by kevzlou7979** [comment]
@gaston2303  You can use ValueChangeEvent on date picker to obtain the value set

**Comment by gaston2303** [comment]
Hello. thank you. 

I tried but it did not work
Can you explain more?

My case, i have three columns, date 1, date 2 and "differents hours" (date 2 - date 1). When retrieve from database to populate the data table, just only have date 1. After retrieve, i put manually date 2 and automatically i want rest date 2 less date 1 and put in the field "differents hours" the difference between them

Thank you
Gastón
