### ISSUE TITLE
Example: AsyncPageTable

### ISSUE THREAD

**Issue by kyr0** [GwtMaterialDesign/gwt-material-table#4]
I tried to implement an AsyncPageTable but all my attempts failed. 

I was using a ListDataSource, overwriting the load(startIndex, viewSize) method to call a presenter method when the list has to load data from a remote data source. When the presenter has loaded it's List of models, those were passed to the ListDataSource's .add(startIndex, list) method. But the row data were never shown (even tho the data was loaded correctly and assigned correctly to the right index (0) of the DataSource instance. 

I played around a lot with different ways of finding a way that works. I even ended up with setting pager and all it's properties manually; calling refreshView(), calling setRedraw(true), setVisibleRange() etc. pp. but I never saw the data actually rendered with an Async data source. 

In the end I tried to use InfiniteDataSource and this worked right away, out-of-the-box.

But could you please create a working example of an AsyncPageTable connected to a (Async)ListDataSource that is filled with data dynamically from a remote data source? (including paging, sorting etc.) This would be great! :-)

**Comment by BenDol** [comment]
As of right now an AsyncListDataSource isn't available. Reason for this is that the InfiniteDataSource served this purpose quite well. However this is something that could be added too.

**Comment by kyr0** [comment]
Okay, fine. I didn't tested that yet, but could I combine the InfiniteDataSource with a Pager?

**Comment by BenDol** [comment]
The InfiniteDataSource makes a pager redundant as the data will load lazily (as seen on the demo application), you can scroll to the section of data you are interested in viewing. You can see how it works in the sample application as it requires a few things from the source when requesting data.

See:
* [PersonDataSource.java](https://github.com/GwtMaterialDesign/gwt-material-table-sample/blob/master/src/main/java/gwt/material/design/sample/client/ui/datasource/PersonDataSource.java#L35) - this is the call that loads the data asynchronously. It requires the absolute row total value to configure the table to know how large the scroll bar needs to be (in the example people.getAbsoluteTotal()) so make sure this value represents the total rows of the data.
* [PersonServiceImpl.java](https://github.com/GwtMaterialDesign/gwt-material-table-sample/blob/master/src/main/java/gwt/material/design/sample/server/PersonServiceImpl.java) - This is the sample server side service that feeds the data. The sample is using categorizations so it takes into account the data's category.

**Comment by Hacker-CB** [comment]
Now async paging with remote sorting should work: https://github.com/GwtMaterialDesign/gwt-material-table/commit/85887688a0e003155bdf8709107cb921ad0b8bfa
