### ISSUE TITLE
Missing method in dataview to update a model

### ISSUE THREAD

**Issue by tbenbrahim** [GwtMaterialDesign/gwt-material-table#40]
In an infinite data view, I wanted to update the rendering of a row for a model without reloading the data from the data source.

I had to add this:
```
public void modelUpdated(final T model) {
		RowComponent<T> modelRow = null;
		for (final RowComponent<T> row : rows) {
			if (row.getData().equals(model)) {
				modelRow = row;
				break;
			}
		}
		if (modelRow != null) {
			modelRow.setRedraw(true);
			modelRow.setData(model);
			renderComponent(modelRow);
		}
	}
```
and the corresponding call in MaterialDataTable. Seems like it would be something to consider adding. to `AbstractDataView`, or did I miss something obvious?

**Comment by BenDol** [comment]
`updateRow(model)`
