### ISSUE TITLE
MaterialDataTable.removeColumn does not completely remove column?

### ISSUE THREAD

**Issue by zolyfarkas** [GwtMaterialDesign/gwt-material-table#49]
After calling MaterialDataTable.removeColumn column is still in the column selector menu....

using 2.0 rc4

**Comment by kevzlou7979** [comment]
@zolyfarkas Thanks for catching this.

Fixed via https://github.com/GwtMaterialDesign/gwt-material-table/commit/c16bb2f566a1956435f0545b0a91cd1ff72cccde
