### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material-table#50]
I have  such options
```
    <inherits name="gwt.material.design.GwtMaterialWithJQuery"/>
    <inherits name="gwt.material.design.GwtMaterialTable"/>
    <inherits name="gwt.material.design.jquery.JQuery"/>
    <inherits name="gwt.material.design.GwtMaterialDesignBasic"/>
    <inherits name="gwt.material.design.themes.ThemeBlue"/>
```
Componetns from gwt-materialdesign work fine

But materialtables... Not =(
![tables](https://cloud.githubusercontent.com/assets/439337/24693946/9f8260ce-19e8-11e7-917b-d4bdeeb66ca3.png)

**Comment by kevzlou7979** [comment]
It seems that the ```.top-panel``` class overrides the theme specified css attribute for this panel. Please update your gwt-material themes in order for the patch worked.

Fixed via https://github.com/GwtMaterialDesign/gwt-material-themes/commit/4aca02c42de7c9c723dd9ff357298e202bad0687

**Comment by LeshaRB** [comment]
<dependency>
                <groupId>com.github.gwtmaterialdesign</groupId>
                <artifactId>gwt-material-themes</artifactId>
                <version>${gwt-material-themes.version}</version>
                <scope>provided</scope>
            </dependency>

Try 2.0 and 2.1
There are nothing new =(

Can you explain on what basis do you update the snapshot version?

**Comment by kevzlou7979** [comment]
Can you checked it now, I fixed the snapshot deployment now.
