### ISSUE TITLE
Popupmenu

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material-table#51]
The pop-up menu should calculate the height of the widget
And float up or down

![table1](https://cloud.githubusercontent.com/assets/439337/24693964/b2a62c58-19e8-11e7-8157-cb697071ba33.png)

**Comment by kevzlou7979** [comment]
Can you explain a little further what exactly the issue? Thanks in advance

**Comment by LeshaRB** [comment]
I create table
    <m.table:MaterialDataTable ui:field="consoleTable" height="100%" useStickyHeader="false" useCategories="false" useRowExpansion="false" selectionType="MULTIPLE"/>

Insert it in bottom of main widget
Add 10 columns without data

And open this menu
![table111](https://cloud.githubusercontent.com/assets/439337/24742568/86519388-1ab3-11e7-8528-8f20985bb890.png)

**Comment by LeshaRB** [comment]
But in some situatuions open normal

![table333](https://cloud.githubusercontent.com/assets/439337/24742647/d0c5e770-1ab3-11e7-9f0e-5906b62a0e98.png)

**Comment by kevzlou7979** [comment]
I assume, you have a css issue into one of your table's parent element, I expect you have ```overflow: hidden``` somewhere which causes your popmenu to  be cut. I tried on the demo showcase to remove all the data / rows. Seems to work as expected.

Example of not having ```overflow: hidden``` container that wraps your table
![image](https://cloud.githubusercontent.com/assets/3138071/25364485/7ab264a8-2995-11e7-95d8-52512c2b1f66.png)

Example of having ```overflow: hidden``` container that wraps your table.
![image](https://cloud.githubusercontent.com/assets/3138071/25364512/9ad74410-2995-11e7-967b-a755d5feedc8.png)

**Comment by LeshaRB** [comment]
I dpn't have such style

Also for example


![datepicker](https://cloud.githubusercontent.com/assets/439337/25382830/f2bcb60c-29c1-11e7-9c31-7ca530be855f.png)

**Comment by LeshaRB** [comment]
But when I delete waves="LIGHT" from MaterialPanel all work fine

[.waves-effect {
    position: relative;
    cursor: pointer;
    display: inline-block;
    overflow: hidden;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
    vertical-align: middle;
    z-index: 1;
    will-change: opacity, transform; - problem in this style
    transition: all .3s ease-out;
}](url)

**Comment by kevzlou7979** [comment]
@LeshaRB  Probably that's the cause of the issue as the ```position: relative``` is used on ```.waves-effect ``` class.
