### ISSUE TITLE
Table header

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material-table#52]
`<span class="table-header">Дата блокировки</span>`

```
th span {
    display: inline-block;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    /* max-width: 100px; */
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;

```
Why does the table header have a maximum width of 100px?

**Comment by kevzlou7979** [comment]
@LeshaRB , it's the initial maximum width required to build each table header, but btw you can easily override thru css if you want, or turn it off by ```max-width: inherit ```
