### ISSUE TITLE
How to set up row height?

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material-table#53]
Using this:
`        standardTable.setRowHeight(33);`
don't change anything.

**Comment by kevzlou7979** [comment]
Thanks for catching will work on this issue now

**Comment by kevzlou7979** [comment]
Hi upon digging in to the issue, I found out that ```expectedRowHeight``` always returns the ```calculatedRowHeight``` which is always 55. 

https://github.com/GwtMaterialDesign/gwt-material-table/blob/master/src/main/java/gwt/material/design/client/data/BaseRenderer.java#L82

**Comment by kevzlou7979** [comment]
@BenDol  Any idea, why it seems that the variable ```expectedRowHeight``` in ```BaseRenderer``` always returns the original value?

**Comment by kevzlou7979** [comment]
@masterdany88 I found a workaround for the setRowHeight(), for the solution you need to redraw your table to make the row height applied.

```
        table.setRowHeight(400);
        table.setRedraw(true);
        table.refreshView();
```

@BenDol Is this required to redraw the table when setting the row height , in order for it to be applied?

**Comment by kevzlou7979** [comment]
![table-row-height](https://cloud.githubusercontent.com/assets/3138071/25575533/f0e068b0-2e8a-11e7-8e29-3d77078ae75d.gif)
