### ISSUE TITLE
Uncaught TypeError: Cannot read property 'textMixin' of undefined

### ISSUE THREAD

**Issue by 81689261** [GwtMaterialDesign/gwt-material-table#57]
hi,
I just created a test project with tbroyer's gwt-maven-plugin with only one EntryPoint class:
```
public class Main implements EntryPoint {
    @Override
    public void onModuleLoad() {
        MaterialDataTable pageTable = new MaterialDataTable();
        pageTable.getTableTitle().setText("Table");
    }
}
```
after "mvn package" the project, the module was compiled successfully.  and when accessing the host page, the browser's console printed out this message:
```
websites-0.js:2341 Uncaught TypeError: Cannot read property 'textMixin' of undefined
    at Array.init (websites-0.js:2341)
    at initializeModules (websites-0.js:39)
    at apply_0 (websites-0.js:630)
    at entry0 (websites-0.js:679)
    at websites-0.js:653
    at gwtOnLoad_0 (websites-0.js:52)
    at websites-0.js:7978
init	@	websites-0.js:2341
initializeModules	@	websites-0.js:39
apply_0	@	websites-0.js:630
entry0	@	websites-0.js:679
(anonymous)	@	websites-0.js:653
gwtOnLoad_0	@	websites-0.js:52
(anonymous)	@	websites-0.js:7978
```

and the version of gwt-material is 2.0-rc4, the version of gwt-material-table is 1.0-rc4. the gwt version is 2.8.1

**Comment by kevzlou7979** [comment]
Can you provide us a simple zip file of your project, as for now we are just using mojo plugins, because we have some issues migrating to tbroyer, On that case we will be having tbroyer plugin to be migrated on GMD 2.1.

**Comment by 81689261** [comment]
Because my server side is a little complicated, I have made a runnable package for you with a minor of modifications. Here is the project，
[test.zip](https://github.com/GwtMaterialDesign/gwt-material-table/files/969488/test.zip)

By running, you can:
in one terminal `cd test&&mvn gwt:codeserver` and in another terminal `cd test&&mvn tomcat7:run`, access `http://localhost:8080`
or, you can `cd test&&mvn package` then deploy the generated war. It issues the similar problems.

**Comment by kevzlou7979** [comment]
Hi @81689261,

Thanks for the fast reply, I can now test the project (Thanks for this). I'am able to run the tbroyer integration on GMD (Interesting) .

In order to make your app works. You need first to add your datatable into the DOM before setting the text of the title. That's why you were having some DOM undefined issue. 

```java
        MaterialDataTable pageTable = new MaterialDataTable();
        // Add first your data table into the RootPanel
        RootPanel.get().add(pageTable);
        // Then access the table title element to set text 
        pageTable.getTableTitle().setText("Table");
```

Here's the screenshot
![image](https://cloud.githubusercontent.com/assets/3138071/25606991/048ef8d8-2f47-11e7-9b56-928bf67f6ae2.png)

**Comment by 81689261** [comment]
@kevzlou7979

**Comment by 81689261** [comment]
@kevzlou7979, Thanks for your reply and It works for now. IMHO, It is better to initialize everything on widget construction other than setup at onLoad.
