### ISSUE TITLE
MaterialDataPager is initialized twice

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material-table#60]
MaterialDataPager is initialized twice, once in MaterialWidget.onLoad and once in MaterialDataPager.onLoad. The next button is bound twice, skipping a page when next is pressed.

**Comment by kevzlou7979** [comment]
Thanks for catching this one. Fixed via https://github.com/GwtMaterialDesign/gwt-material-table/commit/21a2eeb4a36809ed25801d85bffca3dcd3faac83.

**Comment by simerlec** [comment]
can we get an estimate when this will be merged? :)

**Comment by kevzlou7979** [comment]
We will merge / release 2.0 if there's no upcoming bugs.

**Comment by simerlec** [comment]
No, i was wondering if you could merge this fix into the current gwt table 2.0 snapshot because it pretty much breaks the pager :)

**Comment by mitchmartin** [comment]
+1 from me, this does break the pagination.

When will it be merged?

Is there a solid workaround in the meantime?

**Comment by dcdh** [comment]
workaround here: https://github.com/GwtMaterialDesign/gwt-material-table/pull/106
