### ISSUE TITLE
MaterialDataTable missing "hide-on-all"

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material-table#63]
Hi
If you want to hide a table-column (equal a Person-ID) **on all devices** i found no possibility to do this.
The best thing i found is to hide on medium device and up.
```
        @Override
        public HideOn getHideOn() {
           return HideOn.fromStyleName("hide-on-med-and-up");
        }
```
but on a small device (0 - 520px) the ID-column is shown.
Using GMD 2.0-rc5
Thanks

![hideon](https://user-images.githubusercontent.com/24357072/27177082-77b2c286-51c5-11e7-908e-26ead29fbb71.gif)

**Comment by BenDol** [comment]
Any reason you cant get the 'id' of the person from the model object on the table?

**Comment by HoochSDS** [comment]
I want to hide the ID-Column on all device.

**Comment by BenDol** [comment]
See this issue https://github.com/GwtMaterialDesign/gwt-material-table/issues/64
