### ISSUE TITLE
InfiniteDataTable - CustomCategoryComponent not rendering custom category icons.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#65]
Hi @BenDol ,

The icons are still + / - instead of my custom implementation of folder open / close. 
Here is the sample project to reproduce the project. 
https://github.com/GwtMaterialDesign/gwt-material-demo/tree/bug/table_65
Thanks in advance.

![image](https://user-images.githubusercontent.com/3138071/27314952-76e0016a-55a9-11e7-8afd-7ce10ba7e6b7.png)

**Comment by BenDol** [comment]
Since we are loading the categories manually with the infinite scroller you need to do it like so:
```java
        CustomCategoryFactory categoryFactory = new CustomCategoryFactory();
        table.setCategoryFactory(categoryFactory);

        // Load the categories from the server
        table.setLoadMask(true);
        personService.getCategories(new AsyncCallback<List<String>>() {
            @Override
            public void onSuccess(List<String> categories) {
                for(String category : categories) {
                    table.addCategory(categoryFactory.generate(category));
                }
                table.setLoadMask(false);
            }
            @Override
            public void onFailure(Throwable throwable) {
                GWT.log("Getting people categories async call failed.", throwable);
            }
        });
```

**Comment by BenDol** [comment]
I will add `addCategory(String)` to avoid this use case issue.

**Comment by BenDol** [comment]
Added the use case https://github.com/GwtMaterialDesign/gwt-material-table/commit/e4598bbfbe26959be536ec1c9f34826c1026bd89

Just change this now:
```java
for(String category : categories) {
    table.addCategory(category);
}
```

**Comment by kevzlou7979** [comment]
Thanks will try this out.

**Comment by kevzlou7979** [comment]
It's working great :) Thanks @BenDol
