### ISSUE TITLE
Table set default sort column

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material-table#66]
Hello,

this might be a pretty easy question but I cannot find an answer for it in the code.

Is there a way to set a specific column as the default sort - if I have a table with a few columns I want to have the table sorted after the first column by default.

thanks and kind regards

**Comment by simerlec** [comment]
Made myself a quick workaround to this problem:

```java
myTable.getColumns().get(0).setDefaultSortAscending(false);   //set ascending/descending order
JQueryElement $tableHeader = $(myTable);
clickElement($tableHeader.find(".table-header").get(0));

public static native void clickElement(Element elem) /*-{
        elem.click();
}-*/;
```

**Comment by BenDol** [comment]
As an example it is done like so in the latest snapshot:
```java
table.addColumn(new TextColumn<Person>() {
	@Override
	public boolean defaultSortAscending() {
		return false;
	}

	@Override
	public Comparator<? super RowComponent<Person>> sortComparator() {
		return (o1, o2) -> o1.getData().getLastName().compareToIgnoreCase(o2.getData().getLastName());
	}

	@Override
	public String getValue(Person person) {
		return person.getLastName();
	}
});
```

**Comment by BenDol** [comment]
You can also open categories using `openCategory` or close them using `closeCategory`.

**Comment by BenDol** [comment]
In terms of automatically selecting the sort row, this can be implemented.

**Comment by BenDol** [comment]
Can now auto sort columns:
```java
table.addColumn(new TextColumn<Person>() {
	...

        @Override
        public boolean autoSort() {
            return true;
        }

	...
});
```

**Comment by simerlec** [comment]
Just tried to use the new feature and it does not seem to work for me - table is still unsorted.

Gonna try it in a new project as soon as I have time, to see if it's an issue with my current project.

Thanks

**Comment by BenDol** [comment]
Should be working fine, let me know if you figure out how to reproduce the issue. Will reopen soon.
