### ISSUE TITLE
Table Subheader wrong position inside a modal.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#67]
Hi @BenDol 

Having a DataTable with Categories inside a modal - when scrolling the subheader left / top position are miscalculated.

Best Regards,
Kevin

![image](https://user-images.githubusercontent.com/3138071/27778365-e2468b48-5fec-11e7-992b-eb0d08263a93.png)

**Comment by BenDol** [comment]
Please provide the implementation with any custom CSS. Or PM me the implementation.

**Comment by kevzlou7979** [comment]
This has been fixed on recent commit, thanks @BenDol
