### ISSUE TITLE
Table - table.clearCategories();

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#69]
When trying to clear some categories and refresh the datatable - it throws a ```NoSuchElementException``.

See logs below:
![image](https://user-images.githubusercontent.com/3138071/27828807-c1acad9a-60f0-11e7-8ef0-46f58f45e666.png)
`

**Comment by simerlec** [comment]
Please merge this fix as soon as possible!!

**Comment by kevzlou7979** [comment]
Yeah We are working on this specially thanks @BenDol  for the fixed.
