### ISSUE TITLE
Infinite DataTable - data missing when scrolling down quickly

### ISSUE THREAD

**Issue by KenMills** [GwtMaterialDesign/gwt-material-table#74]
If I use the scroll bar and scroll down past the data, no data is displayed.

I can see the data in the browser if I hit F12, but it isn't visible.
![datatable](https://user-images.githubusercontent.com/12837618/28045734-c922870a-6593-11e7-9387-7a7f6e5dac42.gif)

**Comment by kevzlou7979** [comment]
Yeah seems this issue is valid and needs to be fixed before closing 2.0.

**Comment by BenDol** [comment]
This was resolved in my latest fixes on the snapshot.

**Comment by BenDol** [comment]
Check to confirm http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#datatable

**Comment by KenMills** [comment]
The snapshot demo works, but when I try the snapshot with my app I get an exception.

I'm not using categories and get an exception in InfiniteDataView::render int catHeight = getCategoryHeight();

**Comment by BenDol** [comment]
@KenMills the exception should be resolved in the latest snapshot.

**Comment by kevzlou7979** [comment]
I can confirm that this bug is not seen in latest snapshot.
