### ISSUE TITLE
DataTable - table.addRefreshComplete

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#76]
```table.addRefreshComplete``` using this method will be benificial.
```table.addOnReady``` or anything that we will know that the table is finish loading up the datasource and populated to the datatable. (Suggest any name if possible)

Best Regards,
Kevin

**Comment by BenDol** [comment]
See 0aa970d7981b1c8dc3b879eb6b201cd9fb5b4966

**Comment by BenDol** [comment]
Fixes are in the latest SNAPSHOT and the rc6

**Comment by kevzlou7979** [comment]
Ok thanks will put all of this on documentation specially the DataTable section on 2.0-rc6 demo showcase.
