### ISSUE TITLE
gwt-material-table is absent in maven repository

### ISSUE THREAD

**Issue by Zicu81** [GwtMaterialDesign/gwt-material-table#8]
Through Ivy or maven is impossible to find gwt-material-table
"unresolved dependency: com.github.gwtmaterialdesign#gwt-material-table;+: not found"

**Comment by BenDol** [comment]
Sorry for the late response! The 1.0-rc1 has been release along with 1.0-SNAPSHOT for bleeding edge changes. Please let me know if you you are having any troubles.
