### ISSUE TITLE
Frozen Columns

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#83]
Currently in 2.1-SNAPSHOT or [release_2.1 branch](https://github.com/GwtMaterialDesign/gwt-material-table/tree/release_2.1)

**Comment by BenDol** [comment]
![frozen-col-done](https://user-images.githubusercontent.com/1935706/28803787-3184adac-76b3-11e7-9149-3359edd16998.gif)
