### ISSUE TITLE
GMD-Table RC6 old loading issue #28

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material-table#85]
Hi, after the Major loading improvements to address #19 & #11. 
The table load again on each back navigation (attach).
Same issue on GWT-Material Demo.
By the way: The old  RC5 setLoadedCallback method worked perfect in GWTP.
```
    table.setLoadedCallback(new LoadedCallback() {
      @Override
      public void onLoaded() {
        initTable();	// add Column and Handlers
      }
    });
```
Thank you very much

**Comment by BenDol** [comment]
Ah yea, out of curiosity is it causing any exceptions?

**Comment by BenDol** [comment]
You don't need to use the load callback anymore, you can add your columns and rows in the constructor of your View. Try moving the load callback code into the View constructor and let me know.

**Comment by HoochSDS** [comment]
Hi in GWTP the new table initialization (rc6) is not working and you get many exception 
and a really strange program behavior.

I hope I can show you with my Example:
As soon you write code against the table-field, the IDE gives you some different Errors. 
(Type-Error or superclass error)

![error](https://user-images.githubusercontent.com/24357072/29140896-722d2074-7d4c-11e7-8044-0049faf3491a.PNG)

Look here:
![table_rc6](https://user-images.githubusercontent.com/24357072/29140969-a60cee10-7d4c-11e7-957d-3bcd64076af2.gif)

- you can compile the Program without errors, but as soon the table get touched
  you get a exception on the first table-field.  Example: setVisible

```
Exception caught: Exception caught: (TypeError) : Cannot read property 'setVisible_0_g$' of undefined
  mKh_g$	
  Leh_g$	
  Zdh_g$	
  Ydh_g$	
  ueh_g$	
  NZc_g$	
  _X_g$	
  OX_g$	
  (anonymous function)	
>Exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : Cannot read property 'setVisible_0_g$' of undefined
  Error: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : Cannot read property 'setVisible_0_g$' of undefined
```
I don't know, what's going on here, but I can't run the table-addin rc6 in GWTP.
Thank you

Here is my GWTP-View
```
public class TestTab2View extends ViewWithUiHandlers<TestTab2UiHandlers> implements TestTab2Presenter.MyView {
  interface Binder extends UiBinder<HTMLPanel, TestTab2View> {
  }

  @UiField
  MaterialDataTable<TestDTO> table;

  @Inject
  TestTab2View(Binder binder) {
    initWidget(binder.createAndBindUi(this));

    initTable();      // Load Tabledefinition
  }

  private void initTable() {
    
    // Add the tables columns
    table.addColumn(new TextColumn<TestDTO>() {
      @Override
      public Comparator<? super RowComponent<TestDTO>> sortComparator() {
        return (o1, o2) -> o1.getData().getFirstname().compareToIgnoreCase(o2.getData().getFirstname());
      }

      @Override
      public String getValue(TestDTO object) {
        return object.getFirstname();
      }
    }, "Firstname");

    table.addColumn(new TextColumn<TestDTO>() {
      @Override
      public String getValue(TestDTO object) {
        return object.getName();
      }
    }, "Name");

    table.setDestroyOnUnload(false);
  }

  public void setSearchTableData(List<TestDTO> result) {
    table.setVisibleRange(0, result.size());
    table.setRowData(0, result);
    table.refreshView();
  }
}
```

**Comment by BenDol** [comment]
Well you're attempting to manipulate the DOM before it is attached, in the case of accessing the stretch icon for example should be in the onLoad, however I could change it so all the widgets are created in the construction to avoid these issues. BUT there should be a standard to how we manage our widgets and generally onLoad/onUnload should be managed by your application.

**Comment by HoochSDS** [comment]
Hi The IDE-Live code analysis (IDEA) shows there is something wrong. This is not in my hand.
In GWTP I (we) have this DOM manipulation and onLoad problem since the beginning. See #19 #48 #28

Only DataTable RC5 with the Callback-Function was working perfect.

The GMD-Demo Table RC-6 shows this "Load" problem again

Look here:

![gmdtabledemorc6](https://user-images.githubusercontent.com/24357072/29206332-cded0da8-7e81-11e7-96f0-9c879d77e931.gif)

Thanks

**Comment by BenDol** [comment]
The data table hasn't been updated yet. None the less I will readd the load callback for the time being in the SNAPSHOT. However I will be updating as I mentioned in my last message.

**Comment by BenDol** [comment]
Readded the callback for now 3a37978a1b4d81689a6c1d3f3210f199c43ffa69

**Comment by HoochSDS** [comment]
Great! 

2.0-SNAPSHOT\gwt-material-table-2.0-20170811.101807-64.jar tested and the Tables in the GWTP-Application are working again;  :smiley:
Only the Deprecated Warnings are annoying. But somehow l have to live with this.  :wink:

Thank you!

**Comment by BenDol** [comment]
Great. So now everything can be done in the constructor, so the setLoadCallback isn't required anymore. Feel free to test it and let me know if you have any troubles.

**Comment by HoochSDS** [comment]
Hi, First the good news:
 - The IDE-Live code analysis (IDEA) issue: has gone

But with the new 2.0-SNAPSHOT\gwt-material-table-2.0-20170821.231700-83.jar 
no table can be loaded (REST).

The following exception is thrown.

```
(TypeError) : this.loaderTask_0_g$.delay_3_g$ is not a function
  k1h_g$	
  Jxh_g$	
  Xwh_g$	
  Wwh_g$	
  sxh_g$	
  R_c_g$	
  _X_g$	
  OX_g$	
  (anonymous function)	
>Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : this.loaderTask_0_g$.delay_3_g$ is not a function
  TypeError: this.loaderTask_0_g$.delay_3_g$ is not a function
    at HEf_g$.fFf_g$ [as requestData_2_g$] (App-0.js:79320:24)
    at HEf_g$.nFf_g$ [as updateRows_0_g$] (App-0.js:79376:8)
    at HEf_g$.OSj_g$ [as refresh_1_g$] (App-0.js:79243:8)
    at WDi_g$.fEi_g$ [as setSearchTableData_0_g$] (App-0.js:122568:40)
    at kDi_g$.nDi_g$ [as onSuccess_9_g$] (App-0.js:122290:52)
    at kDi_g$.mDi_g$ [as onSuccess_0_g$] (App-0.js:122283:8)
    at wre_g$.xne_g$ [as onExecuteSuccess_0_g$] (App-0.js:52706:22)
    at wre_g$.yne_g$ [as onExecuteSuccess_1_g$] (App-0.js:52710:8)
    at wre_g$.Cre_g$ [as onExecuteSuccess_1_g$] (App-0.js:53855:38)
    at wre_g$.Dre_g$ [as onResponseReceived_1_g$] (App-0.js:53865:10)
    at Hre_g$.Jre_g$ [as onResponseReceived_0_g$] (App-0.js:53924:23)
    at vyc_g$.yyc_g$ [as fireOnResponseReceived_0_g$] (App-0.js:25043:17)
    at Fzc_g$.Gzc_g$ [as onReadyStateChange_0_g$] (App-0.js:25351:28)
    at XMLHttpRequest.<anonymous> (App-0.js:49285:18)
    at LX_g$ (App-0.js:14566:28)
    at OX_g$ (App-0.js:14622:16)
    at XMLHttpRequest.<anonymous> (App-0.js:14602:14)
    k1h_g$	
    m1h_g$	
    l1h_g$	
    Jxh_g$	
    Xwh_g$	
    Wwh_g$	
    sxh_g$	
    R_c_g$	
    _X_g$	
    OX_g$	
    (anonymous function)	
  <console.groupEnd
```
When I switch back to rc6 with the setLoadCallback function all is working fine!
Thanks

**Comment by BenDol** [comment]
This error doesn't make any sense, are you extending and overriding any default InfiniteDataView methods?

Seems like a bad cache issue, can you make sure your cache is cleaned and try again?

If it still isn't working can you send me the basic implementation for me to look at? See if I can spot the issue.

Thanks!

**Comment by HoochSDS** [comment]
Hi, may be the exception above was really a cache issue.
But I was skeptical and did some Tests and find out:

  - With the **MaterialDataTable** widget all is working correctly. :+1:

![untitled](https://user-images.githubusercontent.com/24357072/29612627-76460cd2-8802-11e7-8eee-feebc6e7b052.gif)

  - With the  **MaterialInfiniteDataTable** --> strange things happen

First you get a endless loop at **table.getView().refresh()**;. And If you comment out the line
you get the table but the addRowSelectHandler is never fired.

Look here:
![untitled2](https://user-images.githubusercontent.com/24357072/29612713-e357707c-8802-11e7-9ebc-d6f49381e29e.gif)

I have change all MaterialInfiniteDataTable to MaterialDataTable in my project.
Here is the GWTP-View: File to the GIF's above
Thanks
```
public class TestTab2View extends ViewWithUiHandlers<TestTab2UiHandlers> implements TestTab2Presenter.MyView {
  interface Binder extends UiBinder<HTMLPanel, TestTab2View> {
  }

  @UiField
  MaterialDataTable<TestDTO> table;
// MaterialInfiniteDataTable<TestDTO> table;

  @Inject
  TestTab2View(Binder binder) {
    initWidget(binder.createAndBindUi(this));
//    table.setLoadedCallback(new LoadedCallback() {
//      @Override
//      public void onLoaded() {
//        initTable();      // Load Tabledefinition
//      }
//    });
    initTable();
  }

  private void initTable() {
    table.getStretchIcon().setVisible(false);

    table.addColumn(new TextColumn<TestDTO>() {
      @Override
      public String getValue(TestDTO testDTO) {
        return null;
      }
    });
    // Add the tables columns
    table.addColumn(new TextColumn<TestDTO>() {
      @Override
      public Comparator<? super RowComponent<TestDTO>> sortComparator() {
        return (o1, o2) -> o1.getData().getFirstname().compareToIgnoreCase(o2.getData().getFirstname());
      }

      @Override
      public String getValue(TestDTO object) {
        return object.getFirstname();
      }
    }, "Firstname");

    table.addColumn(new TextColumn<TestDTO>() {
      @Override
      public String getValue(TestDTO object) {
        return object.getName();
      }
    }, "Name");

    table.addRowSelectHandler((event, testDTO, element, aBoolean) -> {
      MaterialToast.fireToast("Hello Select-Row Event");		// never reached with MaterialInfiniteDataTable
      return true;
    });

    table.setDestroyOnUnload(false);
  }

  public void setSearchTableData(List<TestDTO> result) {
    table.setVisibleRange(0, result.size());
    table.setRowData(0, result);
    table.getView().refresh();						// causes endless Loop with MaterialInfiniteDataTable
  }									// you can comment this line out, then you get the table,
									// but the addRowSelectHandler is never fired
}
```

**Comment by BenDol** [comment]
Thanks for the information, can you try it on the latest snapshot (updated recently) I made a few fixes to the InfiniteDataView that might resolve these issues.

**Comment by HoochSDS** [comment]
Hi, I tested the latest MaterialInfiniteDataTable 
2.0-SNAPSHOT\gwt-material-table-2.0-20170821.231700-83.jar 
but the behavior has not changed.

**Comment by HoochSDS** [comment]
Hi, Attention
In gwt-material-table-2.0-20170824.233802-89.jar is a new issue: in AbstractDataView.class :697
Code:
```
....
            pageSizeChanged = pageStart - start;
            if(this.getVisibleItemCount() > 0 && pageSizeChanged < pageSize) {
              for(i = 0; i < pageSizeChanged; ++i) {
                this.rows.add((Component)null);
              }
            }
...
```
Exceprtion:
```
Uncaught ReferenceError: WQj_g$ is not defined
  Rvf_g$	
  zzf_g$	
  lambda_0_g$	
  o	
  dispatch	
  r.handle	
Uncaught ReferenceError: WQj_g$ is not defined
  Nvf_g$	
  bzf_g$	
  lambda_0_g$	
  dispatch	
  r.handle
```
