### ISSUE TITLE
Error:  initialize() of type MaterialDataPager<T> must override

### ISSUE THREAD

**Issue by matam** [GwtMaterialDesign/gwt-material-table#88]
After upgrade to RC6 from RC5 this error is during compilation module in superdev mode. The same error at SNAPSHOOT release.

`       [ERROR] Errors in 'jar:file:/........../.m2/repository/com/github/gwtmaterialdesign/gwt-material-table/2.0-SNAPSHOT/gwt-material-table-2.0-20170809.231707-61.jar!/gwt/material/design/client/ui/pager/MaterialDataPager.java'
            [ERROR] Line 62: The method initialize() of type MaterialDataPager<T> must override or implement a supertype method
         Tracing compile failure path for type 'gwt.material.design.client.ui.pager.MaterialDataPager'
            [ERROR] Errors in 'jar:file:/........../.m2/repository/com/github/gwtmaterialdesign/gwt-material-table/2.0-SNAPSHOT/gwt-material-table-2.0-20170809.231707-61.jar!/gwt/material/design/client/ui/pager/MaterialDataPager.java'
               [ERROR] Line 62: The method initialize() of type MaterialDataPager<T> must override or implement a supertype method
         [ERROR] Hint: Check the inheritance chain from your module; it may not be inheriting a required module or a module may not be adding its source path entries properly`

**Comment by BenDol** [comment]
Need to use the latest version, might have been a build issue in that snapshot.
