### ISSUE TITLE
table getSortContext()

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material-table#92]
Hello,

table used to have a method getSortContext() which is used in the MaterialDataPager doLoad method. It seems to have vanished with the latest commits but is still in user by the pager?

Or am I missing something?

thanks and keep up the good work

**Comment by BenDol** [comment]
Here you go: https://github.com/GwtMaterialDesign/gwt-material-table/wiki/2.0-Migration-Guide

**Comment by simerlec** [comment]
Thank you for the fast reply :)
