### ISSUE TITLE
Excessive MaterialPager load time when number of pages is high

### ISSUE THREAD

**Issue by brazeneric** [GwtMaterialDesign/gwt-material-table#98]
Steps to recreate:
1.  In the GWT Material Demo class PageTable, replace the datasource with the following mock—which with the default pager limit of 5, will cause the table to have 1,000 pages:
```
DataSource<Person> dataSource = new DataSource<Person>()
{
    @Override
    public void load(LoadConfig<Person> loadConfig, LoadCallback<Person> callback)
    {
       callback.onSuccess(new LoadResult<>(new ArrayList<>(), 1, 5000));
    }

    @Override
    public boolean useRemoteSort()
    {
        return false;
    }
};
```
2. Compile, launch, and navigate to `/#datatable`

Expected result:
* Page loads within 2 seconds

Actual result:
* Page takes over 100 seconds to load

Comments:
* This seems to be the result of a long running Javascript process for adding page list items to the dropdown in the num-page-panel area.  The load time scales with the number of pages until it gets high enough to crash the browser tab.  Decreasing the reported "total items" or increasing the limit per page (both of which reduce the number of pages) improves performance.
* Chrome performance profile: [gwt-material-pager-2.0rc6-profile.zip](https://github.com/GwtMaterialDesign/gwt-material-table/files/1261470/gwt-material-pager-2.0rc6-profile.zip)

**Comment by saso5** [comment]
I to have the same problem. @BenDol would you be willing to accept a PR for a pager which has a text input instead of dropdown? Something like http://www.jqwidgets.com/wp-content/uploads/2012/02/jquery-grid-server-side-paging.png

Or should I just create my own pager?

**Comment by BenDol** [comment]
Yeah that would be cool, just set it up and we can get it merged.

**Comment by brazeneric** [comment]
@saso5 - We were thinking of doing something similar to your example.  Have you already implemented it?

**Comment by saso5** [comment]
No, I'm on vacation till the 11, so if you are in a hurry feel free to implement it yourself.

**Comment by saso5** [comment]
So this is my suggestion for the MaterialDataPager witch we now use. 
https://gist.github.com/saso5/3c2e3b972b1a047d23a55f49ad31dea3

I've had to override the buildNumPagePanel because the MaterialDataPagerBase uses MaterialListValueBox by default. @BenDol what do you suggest? Variable listPages is protected so it could break other people implementations.

**Comment by saso5** [comment]
I saw that you componentized the MaterialPager in 2.0 so I've changed the implementation of the PageNumberSelection. 

https://github.com/GwtMaterialDesign/gwt-material-table/pull/119
